### ISSUE TITLE
Can't open the simulator on Windows

### ISSUE THREAD

**Issue by bombsimon** [orta/vscode-playdate#10]
Thanks for this plugin that helps with Playdate development!

The current version unconditionally spawns `open args.output` when using the `playdate` launch type. This works well under macOS but no for Windows.

If I want to open my built application from a terminal in Windows it seems like my best shot would be `start args.output/main.pdz` where `args.output` is the `Output.pdx`.

Would file a PR but I've never written a VS Code plugin and not sure what the best workflow for building and testing is. If this is something you think should be supported and you need help I can do some digging and file a PR.

**Comment by bombsimon** [comment]
Well why not, got some time over today and read the docs on how to get started. I ended up creating different commands and arguments for Windows and macOS, added #11 to add support for this.

**Comment by orta** [comment]
Shipped in 0.0.5!
