### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by lunarcloud** [orta/vscode-playdate#15]
I was wondering why this silently failed for me, until i saw the code: it checks 'process.platform' for 'win32' or 'darwin'
but really, every non-windows platform should work with the code you specified as macOS-only (darwin).

If you could make this a simpler if-else, it would likely work for me here on Linux.

**Comment by lunarcloud** [comment]
I think case-sensitivity is now the blocker - causes the compile to fail.
https://github.com/orta/vscode-playdate/blob/42fc4a751cd7e094f305cb1c3e057cae0ea7611f/src/command.ts#L12 

    sam@sam-desktop:~/Other/PlaydateSDK-1.10.0/Examples/Level 1-1$ $PLAYDATE_SDK_PATH/bin/pdc ./Source ./output.pdx 
    Unrecognized file types are copied by default. Use the -k or --skip-unknown flag to skip these files instead.
    Copying level_1-1-old.json
    Copying level_1-1.json

vs

    sam@sam-desktop:~/Other/PlaydateSDK-1.10.0/Examples/Level 1-1$ $PLAYDATE_SDK_PATH/bin/pdc ./source ./output.pdx 
    error: main.lua or pdex.bin required

I believe this would be an issue for *some* macOS users too, but I know a lot of folks run with case-insensitive because Adobe products don't work well with case-sensitive.

**Comment by bombsimon** [comment]
The configuration you refer to is for the debugger where you can configure `source` and `output`. The code you linked is for the command in the _command palette_ which is currently not configurable.

So if you're on Linux, use a case sensitive environment and have your code in `Source`, this will not work. It should work with the debugger if you launch the simulator by hitting F5 however.

To support custom source and output directories from the command palette just like the debugger we should add more properties that could go in the `settings.json` here: https://github.com/orta/vscode-playdate/blob/42fc4a751cd7e094f305cb1c3e057cae0ea7611f/package.json#L33-L38

I can take a stab at this!

**Comment by lunarcloud** [comment]
Yeah, mostly because the examples the SDK ships with uses uppercase, maybe that should be the default assumption at the least. I can and will, in personal projects, use lowercase for everything.

**Comment by bombsimon** [comment]
> Yeah, mostly because the examples the SDK ships with uses uppercase, maybe that should be the default assumption at the least. I can and will, in personal projects, use lowercase for everything.

Oh, that's a miss by me! If it is some de-facto standard (which it seems like, all examples uses it) we should make it the default already in #19. I, like you always uses lowercase letters for files and directories so that's why I went with it in the plugin.

**Comment by lunarcloud** [comment]
this has all been good, and it's *now* allowed me to see the last bug.
