### ISSUE TITLE
"Run App" command failure output

### ISSUE THREAD

**Issue by JosephTLyons** [orta/vscode-playdate#24]
Is there a place where the output of the "Run app" command is logged?  I'm having some issues with compilation errors, but don't know what they are.  I'm able to compile and run the app in the simulator via the terminal, but the command is failing for me.

**Comment by bombsimon** [comment]
Sadly no, we just log that it fails if it fails.

The `compile` (and `run`) methods returns the full result from [`spawnSync`](https://nodejs.org/api/child_process.html#child_processspawnsynccommand-args-options) so we have access to both `stderr` and `stdout`  but it's never used: https://github.com/orta/vscode-playdate/blob/a941f2f890c5f483f985f975d4e99aff2f641f7e/src/command.ts#L25-L29

PRs welcome!

**Comment by bombsimon** [comment]
This was actually changed in #27 but I forgot to mention it here. With that change we will now print the error, stderr and stdout if the compilation failed.

I'll close this issue given that we logg the available output but if there are some other issues feel free to ping for re-open or create a new issue if not relevant to this one.
